#profile routes
import logging
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from supabase import Client

# Import schemas and dependencies
from schema.profile import ProfileUpdate, ProfileResponse
from service.profile_service import ProfileService
from core.dependencies import get_current_user_client

logger = logging.getLogger("billboard_api.profile_routes")

# Router setup with prefix and tags
router = APIRouter(prefix="/profile", tags=["Profile"])

@router.get("/me", response_model=ProfileResponse)
async def get_profile(user_client: Client = Depends(get_current_user_client)):
    """
    Fetch the currently logged-in user's profile.
    This relies on the scoped user_client provided by the dependency.
    """
    logger.info("Get profile requested for user=%s", user_client.current_user.id)
    return ProfileService.get_my_profile(user_client)

@router.put("/me")
async def update_profile(
    profile_data: ProfileUpdate, 
    user_client: Client = Depends(get_current_user_client)
):
    """
    Update the currently logged-in user's profile information.
    """
    logger.info("Update profile requested for user=%s", user_client.current_user.id)
    return ProfileService.update_my_profile(user_client, profile_data)

@router.get("/history")
async def get_ad_history(user_client: Client = Depends(get_current_user_client)):
    """
    Fetches the history of all ads (images and videos) generated by the user.
    Supabase RLS (Row Level Security) ensures the user only sees their own data.
    """
    try:
        user_id = user_client.current_user.id
        logger.info("Fetching ad history for user_id=%s", user_id)
        
        # Query the 'ads' table, ordered by most recent first
        response = user_client.table("ads")\
            .select("*")\
            .order("created_at", desc=True)\
            .execute()
            
        # Logging the count for debugging purposes
        logger.info("Successfully retrieved %d ads for user %s", len(response.data), user_id)
        
        return response.data
        
    except Exception as e:
        logger.error("Failed to fetch ad history for user %s: %s", user_id, str(e), exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, 
            detail="Could not retrieve your ad history from the database."
        )
